version: "3.7"
services:

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    depends_on:
      - webapp
    ports:
      - "8002:80"

  webapp:
    container_name: fala
    build: .
    environment:
      - LAALAA_API_HOST=https://staging.laalaa.dsd.io
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
