version: "3.7"
services:

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    depends_on:
      - webapp
    ports:
      - "8002:80"

  webapp:
    container_name: fala
    build: .
    environment:
      - LAALAA_API_HOST=https://staging.laalaa.dsd.io
      - DJANGO_SETTINGS_MODULE=fala.settings.local
    ports:
      - "8000:8000"
