apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laa-fala
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laa-fala-app
  template:
    metadata:
      labels:
        app: laa-fala-app
    spec:
      containers:
      - image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-get-access/laa-fala-webapp:master
        name: webapp
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: LAALAA_API_HOST
          value: https://staging.laalaa.dsd.io
        - name: DEBUG_STATIC
          value: "True"
      - image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-get-access/laa-fala-nginx:master
        name: nginx
        ports:
        - containerPort: 80
          name: http
